### ISSUE TITLE
Property 'toDataURL' does not exist on type 'Component<SvgProps, any, any>'.ts

### ISSUE THREAD

**Issue by Praveena0989** [software-mansion/react-native-svg#1365]
I am  trying to extract base64 string from svg and It is working fine but typescript is complaining 
`Property 'toDataURL' does not exist on type 'Component<SvgProps, any, any>'.ts
`

Creating ref like this
`   const svgRef = useRef<(React.Component<SvgProps, any, any>) | null>(null);
` 

and using it like this  
 ` <Svg ref={svgRef}`

Here typescript is complaining - Property 'toDataURL' does not exist on type 'Component<SvgProps, any, any>'.ts
` svgRef.current.toDataURL((base64: string) => {})`

**Comment by HAFDIAHMED** [comment]
i have the same issues with qr code svg 
`  const saveQrcode =()=>{
    svg1.current.toDataURL(callback);
  }`

**Comment by WoLewicki** [comment]
Since [this example](https://github.com/software-mansion/react-native-svg/blob/b3dc36ab01d5b6e6335e30f0f442099a3dedef16/Example/src/examples/Svg.tsx#L135) works OK with TS, I believe it is not an issue anymore. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
