### ISSUE TITLE
SVG does not render with react-native-svg, but it renders in Chrome

### ISSUE THREAD

**Issue by yolpsoftware** [software-mansion/react-native-svg#1597]
# Bug

The following SVG does not render in `react-native-svg`:

https://gist.githubusercontent.com/yolpsoftware/b82c92a5bc841207d3bd05259eeb0980/raw/e43b9db8ddaf720d2090ad0227ddea478130eb31/Hong%2520Kong%2520on%2520the%2520Globe%2520(Japan%2520centered).svg

Here's a snack to test it:

https://snack.expo.io/@yolpsoftware/svguri

#### Unexpected behavior

The SVG is not rendered.

## Environment info

Library version: 12.1.0

I also tested it locally with 12.1.1 without success. The Expo snack requires 12.1.0, that's why my snack uses that.

## Steps To Reproduce

1. Go to https://snack.expo.io/@yolpsoftware/svguri
2. Run it on your iOS device

Describe what you expected to happen:

1.The SVG of the globe should render, with Hong Kong highlighted

## Short, Self Contained, Correct (Compilable), Example

https://snack.expo.io/@yolpsoftware/svguri

**Comment by yolpsoftware** [comment]
Any news?

**Comment by CuriosBasant** [comment]
Any updates on this, I've the same issue with this image [SVG Image](https://d9yce0v7jgjpv.cloudfront.net/appicons/people.svg)

See this snack, [Snack Link](https://snack.expo.dev/@basant-hootboard/svguri)

**Comment by willykurmann** [comment]
same issue here,  any update ?

**Comment by jakex7** [comment]
@yolpsoftware @willykurmann **Neither of these** are valid SVGs. There is a lot of junk generated by *Adobe Illustrator* that isn't part of the SVG specification. For example, tags like `sfw` and `sliceSourceBounds` don't exist in the specification, nor does the `bottomLeftOrigin` attribute. To ensure proper rendering, you can export it with `SVG 1.1 compatibility`. While these files may render correctly in browsers, that's because browsers are generally designed to handle a wide range of standards, such as HTML, CSS, XHTML, and more.
