### ISSUE TITLE
[Issue?] Not able to render SVG

### ISSUE THREAD

**Issue by pavankumarj** [software-mansion/react-native-svg#1619]
Not able to render the following SVG, it works fine in the web.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#26A472;}
</style>
<path class="st0" d="M12,2c-1.4,0-2.5,1.1-2.5,2.5S10.6,7,12,7s2.5-1.1,2.5-2.5S13.4,2,12,2z M20.3,6.5c-0.4-1.1-1.5-1.7-2.6-1.3
	l-1.6,0.6c-0.2,0.1-0.3,0.2-0.4,0.4c-0.7,1.4-2.1,2.3-3.7,2.3c-1.6,0-3-1-3.7-2.3C8.2,6.1,8.1,5.9,7.9,5.9L6.3,5.3
	C5.2,4.9,4,5.4,3.7,6.5C3.3,7.5,3.8,8.6,4.8,9L8,10.3v3.1l-2,5.7c-0.4,1,0.2,2.1,1.2,2.5c1,0.4,2.1-0.2,2.5-1.2L11,17
	c0.2-2.8,2.3-5.2,5-5.8v-0.9L19.2,9C20.2,8.6,20.7,7.5,20.3,6.5z M23,17.5c0,3-2.5,5.5-5.5,5.5S12,20.5,12,17.5s2.5-5.5,5.5-5.5
	S23,14.5,23,17.5z M20.9,15.1c-0.2-0.2-0.5-0.2-0.7,0l-3.6,3.6l-1.6-1.6c-0.2-0.2-0.5-0.2-0.7,0c-0.2,0.2-0.2,0.5,0,0.7l2,2
	c0.2,0.2,0.5,0.2,0.7,0l4-4C21,15.7,21,15.3,20.9,15.1z"/>
</svg>
```

Console Error: Cannot read property 'push' of null

**Comment by Adnan-Bacic** [comment]
im having similar problems. im taking over a project where this package was upgraded from 9.13.16 to 12.1.1 recently

i found an svg that is no longer displayed. when i try to do:

`<SvgXml xml={ArrowRight}></SvgXml>`

i get the same error as you.

the current implementation that worked before the package was upgraded looks like this:

```
<Item
          color={theme.colors.secondaryYellow}
          icon={<ArrowRight width={16} height={16} />}
        />
```

and the relevant part of the <Item> component for the svg is just this:

`<>{icon}</>`

since this no longer works i figured id try with the `<SvgXml>` component where i pass an `xml` prop instead of rendering the whole icon as shown above. this is where i get the same error as you.

i also get another error:

```
Console Warning
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'navigate' of null
TypeError: Cannot read property 'navigate' of null
```

and this is just when trying to render the svg. i am not clicking it as it never renders successfully.

**Comment by WoLewicki** [comment]
@pavankumarj I tried to render the specified svg with `SvgCss` component and it worked just fine. As for the `fill="black"` problem, it is already discussed in https://github.com/software-mansion/react-native-svg/issues/1543 with a proposed fix. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
