### ISSUE TITLE
Why does RN SVG not use OS level SVG support

### ISSUE THREAD

**Issue by scottwio** [software-mansion/react-native-svg#1659]
# Question

Does anyone have any idea why this library seems to build out the SVGs manually in Core Graphics and Android graphics? Both Android and iOS support SVGs as of XCode 12 is it not possible to leverage that support? I worry a little that the amount of work going behind the scenes to render all the SVGs in everyone's RN apps is going to harm performance as most people tend to use them over PNGs. Is that worry unfounded?

**Comment by Only-IceSoul** [comment]
Android builds it manually and does not support effects.  Xcode renders the svg to PNG when building the app bundle.

**Comment by msand** [comment]
Also, if you need any state dependent rendering you need something like this library

**Comment by scottwio** [comment]
That's interesting thanks for the information. I keep working on projects where react-native-svg is used to allow developers to use SVGs as they would on the web. All images that are simple enough become an SVG, so normally around 80% - 90% of the images use react-native-svg. Is this a good idea in regards to performance or should react-native-svg only be used where state-dependent rendering is needed?

**Comment by msand** [comment]
I guess it depends on the content, it's probably fine to use for most things. Performance issues are likely to be due to other causes. But if measurements show it to be the costliest part of an app, and the usual ways of optimizing / memoizing react code doesn't fix it, at that point it probably makes sense to look into rendering expensive parts as static raster images, assuming it's fine to loose the fidelity of vector graphics for the app / use case in question.
