### ISSUE TITLE
SvgXml does not work in Expo

### ISSUE THREAD

**Issue by Tozare** [software-mansion/react-native-svg#2075]
# Bug

I have been trying to use SvgXml like in the documentation, however I got error in my Expo snack.

#### Link to my snack

You can find the error by following this link https://snack.expo.dev/@tozare/svgxml-does-not-work

**Comment by bohdanprog** [comment]
Hello @Tozare,

Currently, it is not feasible to use SvgXml in web applications. The detailed reason for this restriction can be found here: [link](https://github.com/software-mansion/react-native-svg/issues/1279#issuecomment-595269518). This issue is a bit complicated.

Be assured that we have this on our roadmap, and we plan to implement it soon. Please stay tuned for further updates.
If you have any other questions, please feel free to ask.
Thank you.
