### ISSUE TITLE
React Native SVG stroke-width bug on expo web. 

### ISSUE THREAD

**Issue by MohammadHarisZia** [software-mansion/react-native-svg#2260]
# Bug
<img width="759" alt="Screenshot 2024-04-18 at 6 14 31 PM" src="https://github.com/software-mansion/react-native-svg/assets/63912301/16e30186-6b4a-4241-bf1e-115aeb6dcf29">
Stroke-width and fill-rule bug in react-native-svg when using on expo web.

Library version: 14.1.0

**Comment by bohdanprog** [comment]
Hello @MohammadHarisZia,
Do you still have that error?
I tried to reproduce that issue, but couldn't.
Let us know if you still have that error, and share an example to reproduce that.

Thank you.

**Comment by edkimmel** [comment]
Just use any path with invalid properties...
```
      <Path
        d="M204.886 98.9847L216.652 95.6615"
        stroke="#926E5B"
        stroke-width="4.90369" // Error, use strokeWidth
        stroke-miterlimit="10" // Error, use strokeMiterlimit
        stroke-linecap="round" // Error, use strokeLinecap
      />

**Comment by bohdanprog** [comment]
Hello @edkimmel,
please check [here](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#svg) the example of how to use react-native-svg.

**Comment by jakex7** [comment]
It appears that the error message is self-explanatory. According to the `react-native-svg` documentation, properties should be passed in camelCase rather than using dashes (`strokeWidth` instead of `stroke-width` etc). As both you and the error message indicate, they are invalid properties when passed with dashes. Therefore, this behavior is intended.
