### ISSUE TITLE
defaultProps issue with React version 18.3

### ISSUE THREAD

**Issue by Manouli** [software-mansion/react-native-svg#2273]
# Bug

I am using react-native-web inside a next js project with the react-native-svg package and the babel-plugin-inline-react-svg. It seems to be working fine. The only problem is that I am getting a warning from all my icons about defaultProps. 

Example warning: 

```
Warning: EmptyDashboardIcon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

We don't declare any defaultProps ourselves so it must be coming from the package.

I tried replacing this setup with the svgr/webpack implementation and that would not throw any errors. Is there something that I am missing?

Library version: ^12.1.1,
"babel-plugin-inline-react-svg": "2.0.1",

**Comment by jakex7** [comment]
Hi @Manouli,
Thank you for reporting this issue. However, I was unable to reproduce it. Could you please provide a minimal reproducible repository?

**Comment by Manouli** [comment]
@jakex7 https://github.com/Manouli/react-native-svg-test I have created a repo for your here.

**Comment by jakex7** [comment]
After a closer inspection, there is no `defaultProps` in any of our files and the warning comes from `babel-plugin-inline-react-svg`. 
Here's the pull request introducing this feature: [Use defaultProps instead of adding props to the svg #8](https://github.com/airbnb/babel-plugin-inline-react-svg/pull/8) 
There's also a related PR where we can find a discussion about this topic. [Provide option for spreading props rather than static assignment #86](https://github.com/airbnb/babel-plugin-inline-react-svg/pull/86)

**Comment by Manouli** [comment]
@jakex7 thank you! 🫡

**Comment by shawna-donnelly** [comment]
I'm gettingn the same issue, and inside of src/elements, it looks like defaultProps is used extensively. I do not use `babel-plugin-inline-react-svg` and am getting the same default props errors for all of our SVGs in our react-native app.
