### ISSUE TITLE
Uniqueness of id's

### ISSUE THREAD

**Issue by JasperH8g** [software-mansion/react-native-svg#731]
Based on the documentation, it is not clear how we should define an id:

> The id prop of the tag defines a unique name for the gradient

What should the context of its uniqueness be here? Should it be unique within this component? Within one specific `<Svg />`, or globally in the entire app?

**Comment by msand** [comment]
I think it should apply within one Svg root, should be straightforward to test ;)

**Comment by miguelocarvajal** [comment]
I tried creating a "global" `<Svg />` tag that holds all of my `<Defs />`, however it seems I cannot use them outside of the `<Svg />` tag that defines them.

I can do so on the web, but not when using react-native-svg.

In other words, the id seems to be within the scope of the component (for native).

**Comment by msand** [comment]
Would prefer not to introduce any global state and ids. Otherwise would need to set up subscriptions for updates or invalidations there as well. You could use the context api to provide a component which contains your Defs, and include this in your Svg components. Or, if the defs are static, just export them from a separate file and then import and compose into any component where you need it.

**Comment by miguelocarvajal** [comment]
@msand We opted for exporting them from a separate file. Just thought I would mention it here because the react-native-svg-web version does support global (because the browser does so) and I spent a bit of time debugging why my gradients weren't showing up on native.

Thanks for your feedback though! :)
